### ISSUE TITLE
MainMenuView 놀이기구예약 연결

### ISSUE THREAD

**Issue by yoaruku** [ssg-240304-java2/JD-5racle#13]

**Comment by Lucas-Choi-17** [comment]
MainMenuView 생성 후 추가하겠습니다.
혹시 직접 추가를 원하시면, AttractionReservationMenu에 UserDTO user 데이터 전달하여 사용하시면 될거같습니다.  이렇게 하시는 경우 메인메뉴에서 [놀이기구 예약, 예약 확인] 선택 단계로 넘어가게 됩니다.
